package com.pi4j.bench.runner;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.stream.Stream;

import static java.nio.file.StandardCopyOption.REPLACE_EXISTING;

/// Materialises the mock kernel-driver sources (C + Makefiles + setup/clean scripts, both
/// the v4 and v3 flavours) that are **embedded in the artifact** into a `mocks/` dir next
/// to where the binary lives, so a bare `pi4j-bench-<arch>` (or fat jar) is self-contained.
///
/// "Built and reused where the binary lives": the tree is extracted once (reused on later
/// runs unless `--rebuild-mocks`), and each flavour's `build.sh` is rewritten to a
/// **reuse-aware** guard — it compiles the `.ko` on the first load and then skips the
/// `apt-get`/`make clean`/`make` churn while the compiled module is still present. The
/// kernel module itself is arch- and kernel-specific, so it's still compiled on the target
/// (the sources + a JDK ride along; the `.ko` is cached beside the binary).
final class MockBuilder {

    private MockBuilder() {}

    /// Extract the embedded mocks under `home/mocks` (idempotent) and return that dir.
    /// `rebuild` forces re-extraction and drops any cached `.ko` so the next load recompiles.
    static Path prepare(Path home, boolean rebuild, boolean dryRun) throws IOException {
        var dest = home.resolve("mocks");
        if (dryRun) return dest; // report paths without touching disk

        var indexBytes = MockBuilder.class.getResourceAsStream("/mocks/INDEX");
        if (indexBytes == null) {
            throw new IOException("embedded mocks/INDEX not on the classpath — the artifact "
                    + "was built without the mock sources (see :bench-runner:embedMocks)");
        }
        List<String> entries;
        try (indexBytes) {
            entries = new String(indexBytes.readAllBytes()).lines().filter(s -> !s.isBlank()).toList();
        }

        if (rebuild) deleteRecursively(dest);
        if (!Files.exists(dest)) {
            for (var rel : entries) { // rel = "mocks/v4/src/test/native/i2c/Makefile"
                var target = home.resolve(rel);
                Files.createDirectories(target.getParent());
                try (var in = MockBuilder.class.getResourceAsStream("/" + rel)) {
                    if (in == null) continue;
                    Files.copy(in, target, REPLACE_EXISTING);
                }
                if (rel.endsWith(".sh")) target.toFile().setExecutable(true);
            }
        }

        rewriteBuildScripts(dest);
        if (rebuild) {
            for (var ko : findKo(dest)) Files.deleteIfExists(ko); // force recompile on next load
        }
        return dest;
    }

    /// Replace each `native/<iface>/build.sh` with a reuse-aware version: compile only when
    /// the `.ko` is missing (or `MOCK_REBUILD=1`), otherwise return immediately.
    private static void rewriteBuildScripts(Path mocks) throws IOException {
        if (!Files.isDirectory(mocks)) return;
        try (Stream<Path> walk = Files.walk(mocks)) {
            for (var sh : walk.filter(p -> p.getFileName().toString().equals("build.sh")).toList()) {
                var iface = sh.getParent().getFileName().toString(); // native/<iface>/build.sh
                Files.writeString(sh, """
                        #!/bin/sh
                        # reuse-aware (generated by MockBuilder): build the mock .ko once, then reuse it.
                        cd "$(dirname "$0")" || exit 1
                        KO=%s-mock.ko
                        if [ "${MOCK_REBUILD:-0}" != "1" ] && [ -f "../../resources/$KO" ]; then
                            exit 0
                        fi
                        apt-get install -y linux-headers-"$(uname -r)" >/dev/null 2>&1 || true
                        make clean >/dev/null 2>&1 || true
                        make
                        cp "$KO" ../../resources/
                        make clean >/dev/null 2>&1 || true
                        """.formatted(iface));
                sh.toFile().setExecutable(true);
            }
        }
    }

    private static List<Path> findKo(Path mocks) throws IOException {
        if (!Files.isDirectory(mocks)) return List.of();
        try (Stream<Path> walk = Files.walk(mocks)) {
            var out = new ArrayList<Path>();
            walk.filter(p -> p.getFileName().toString().endsWith(".ko")).forEach(out::add);
            return out;
        }
    }

    private static void deleteRecursively(Path dir) throws IOException {
        if (!Files.exists(dir)) return;
        try (Stream<Path> walk = Files.walk(dir)) {
            walk.sorted((a, b) -> b.getNameCount() - a.getNameCount()).forEach(p -> {
                try {
                    Files.deleteIfExists(p);
                } catch (IOException e) {
                    throw new RuntimeException(e);
                }
            });
        }
    }
}
